#!/bin/sh

cd ~/.vim/bundle
for bundle in git://github.com/majutsushi/tagbar.git git://github.com/tpope/vim-fugitive.git git://github.com/Lokaltog/vim-powerline.git git://github.com/scrooloose/nerdtree.git; do
  echo "Installing $bundle";
  git clone $bundle
  echo
done;

